=== yangyulin007/JobInfo/ODAC121024_x64/stage/cvu/cv/cvdata/admin.dtd
<!-- DTD for admin data in VDM module, Cluster verification -->

<!--
*  
* RootProperty:
*   As the name indicates, it is the root property
*
* PProperty:
*   Contains an individual property, which has 2 must-have attributes.
*   attr> Name: Name of the property
*   attr> Value: Value of the property
*
-->

<!-- Root property -->
<!ELEMENT RootProperty ( Property ) >


<!-- Property -->
<!ELEMENT Property (NULL) >

<!ATTLIST Property Name  CDATA #REQUIRED >
<!ATTLIST Property Value CDATA #REQUIRED >

=== yangyulin007/JobInfo/ODAC121024_x64/stage/cvu/cv/cvdata/admin.xml
<?xml version="1.0" encoding="ISO-8859-1"  ?>
<!DOCTYPE RootProperty SYSTEM "admin.dtd" >


<!-- 
======================================================================
 CAUTION:                                                             
    Changes to this file might adversely affect Cluster Verification.  

    This file has 2 sections. Section D contains the default values    
    where as Section P contains the platform specific values 
======================================================================= 
-->

<!-- Root property -->
<RootProperty>

  <!-- 
  ===============  SECTION D: [ START ]  ============================
  This section contains the default values for various properties. 
  Generally, these are available/applicable on all the platforms.
  ===================================================================
  -->

  <!-- name of the constraint file -->
  <Property Name ="file_constraints_xml"  
            Value="constraints.xml" />

  <!-- default/current OCR version for this platform -->
  <Property Name="def_ocr_ver"  
            Value="4"/>
  <!-- default/current ocr version for this platform for 11.2-->
  <Property Name="def_ocr_ver_11_2"
            Value="3"/>
  <!-- default/current ocr version for this platform for 11.1-->
  <Property Name="def_ocr_ver_11_0"  
            Value="2"/>
  <!-- default/current ocr version for this platform for 11.1-->
  <Property Name="def_ocr_ver_11_1"  
            Value="2"/>
  <!-- default/current ocr version for this platform for 10.2-->
  <Property Name="def_ocr_ver_10_2"  
            Value="2"/>    
  <!-- default value for 'ocr' size  -->
  <Property Name="def_ocr_size"  Value="262144"/>
  <!-- default value for min space limit in MB for CRS Home to be monitored by FreeSpaceComponent -->
  <!-- modify free space value in message DESC_COMP_FREE_SPACE when below line is modified -->
  <Property Name="def_crshome_freespace_default_limit"
            Value="5120"/>
  <!-- default value for percentage of available space to define the minimum limit for CRS Home -->
  <!-- modify free space percent value in message DESC_COMP_FREE_SPACE when below line is modified -->
  <Property Name="def_crshome_freespace_percentage_limit"
            Value="0.05"/>


  <!--  ********************  SECTION D: [ END ]  *****************  -->


  <!-- 
  ===============  SECTION P: [ START ]  ============================
  This section contains the platform specific properties and their
  values. These values may or may not exist on other platforms. 
  ===================================================================
  -->
  <!--  Name of the remote command(the wrapper script for exectask) -->
  <Property Name ="rem_command"  
            Value="exectask.exe" />
  <!--  Files required on the remote node for exectask operation -->
  <!-- To be changed later -->
  <Property Name ="rem_cmd_files"  
            Value="cv\remenv\exectask.exe,bin\oracore12.dll,bin\orauts.dll,bin\oranls12.dll,bin\oraunls12.dll,bin\msvcr100.dll,bin\msvcp100.dll,cv\remenv\cvuhelper.bat,cv\remenv\jlib" />

  <!-- default temp location on this platform -->
  <Property Name ="def_dir_temp"  
            Value="C:\temp" />

  <!-- CRS Daemon - internal name -->
  <Property Name ="DAEMON_INAME_CRS"
            Value="OracleCRService" />
  <!-- CRS Daemon - display name -->
  <Property Name ="DAEMON_DNAME_CRS"
            Value="CRS daemon" />

  <!-- CSS Daemon - internal name -->
  <Property Name ="DAEMON_INAME_CSS"
            Value="OracleCSService" />
  <!-- CSS Daemon - display name -->
  <Property Name ="DAEMON_DNAME_CSS"
            Value="CSS daemon" />

  <!-- EVM Daemon - internal name -->
  <Property Name ="DAEMON_INAME_EVM"
            Value="OracleEVMService" />
  <!-- EVM Daemon - display name -->
  <Property Name ="DAEMON_DNAME_EVM"
            Value="EVM daemon" />

  <!-- OHASD Daemon - internal name -->
  <Property Name ="DAEMON_INAME_OHASD"
            Value="OracleOHService" />
  <!-- CRS Daemon - display name -->
  <Property Name ="DAEMON_DNAME_OHASD"
            Value="OHAS daemon" />

  <!--  ***************  SECTION P:  [ END ]  ************************  -->

</RootProperty>
